#include <linux/config.h>

#define cons_num	(vc_cons[currcons].d->vc_num)
#define sw		(vc_cons[currcons].d->vc_sw)
#define screenbuf	(vc_cons[currcons].d->vc_screenbuf)
#define screenbuf_size	(vc_cons[currcons].d->vc_screenbuf_size)
#define origin		(vc_cons[currcons].d->vc_origin)
#define scr_top		(vc_cons[currcons].d->vc_scr_top)
#define visible_origin  (vc_cons[currcons].d->vc_visible_origin)
#define scr_end		(vc_cons[currcons].d->vc_scr_end)
#define pos		(vc_cons[currcons].d->vc_pos)
#define top		(vc_cons[currcons].d->vc_top)
#define bottom		(vc_cons[currcons].d->vc_bottom)
#define x		(vc_cons[currcons].d->vc_x)
#define y		(vc_cons[currcons].d->vc_y)
#define vc_state	(vc_cons[currcons].d->vc_state)
#define npar		(vc_cons[currcons].d->vc_npar)
#define par		(vc_cons[currcons].d->vc_par)
#define ques		(vc_cons[currcons].d->vc_ques)
#define attr		(vc_cons[currcons].d->vc_attr)
#define saved_x		(vc_cons[currcons].d->vc_saved_x)
#define saved_y		(vc_cons[currcons].d->vc_saved_y)
#define translate	(vc_cons[currcons].d->vc_translate)
#define G0_charset	(vc_cons[currcons].d->vc_G0_charset)
#define G1_charset	(vc_cons[currcons].d->vc_G1_charset)
#define saved_G0	(vc_cons[currcons].d->vc_saved_G0)
#define saved_G1	(vc_cons[currcons].d->vc_saved_G1)
#define utf		(vc_cons[currcons].d->vc_utf)
#define utf_count	(vc_cons[currcons].d->vc_utf_count)
#define utf_char	(vc_cons[currcons].d->vc_utf_char)
#define video_erase_char (vc_cons[currcons].d->vc_video_erase_char)
#ifdef CONFIG_PC9800
#define video_erase_attr (vc_cons[currcons].d->vc_video_erase_attr)
#endif
#define disp_ctrl	(vc_cons[currcons].d->vc_disp_ctrl)
#define toggle_meta	(vc_cons[currcons].d->vc_toggle_meta)
#define decscnm		(vc_cons[currcons].d->vc_decscnm)
#define decom		(vc_cons[currcons].d->vc_decom)
#define decawm		(vc_cons[currcons].d->vc_decawm)
#define deccm		(vc_cons[currcons].d->vc_deccm)
#define decim		(vc_cons[currcons].d->vc_decim)
#define deccolm		(vc_cons[currcons].d->vc_deccolm)
#define need_wrap	(vc_cons[currcons].d->vc_need_wrap)
#define kmalloced	(vc_cons[currcons].d->vc_kmalloced)
#define report_mouse	(vc_cons[currcons].d->vc_report_mouse)
#define color		(vc_cons[currcons].d->vc_color)
#define s_color		(vc_cons[currcons].d->vc_s_color)
#define def_color	(vc_cons[currcons].d->vc_def_color)
#define foreground	(color & 0x0f)
#define background	(color & 0xf0)
#define charset		(vc_cons[currcons].d->vc_charset)
#define s_charset	(vc_cons[currcons].d->vc_s_charset)
#define	intensity	(vc_cons[currcons].d->vc_intensity)
#define	underline	(vc_cons[currcons].d->vc_underline)
#define	blink		(vc_cons[currcons].d->vc_blink)
#define	reverse		(vc_cons[currcons].d->vc_reverse)
#define	s_intensity	(vc_cons[currcons].d->vc_s_intensity)
#define	s_underline	(vc_cons[currcons].d->vc_s_underline)
#define	s_blink		(vc_cons[currcons].d->vc_s_blink)
#define	s_reverse	(vc_cons[currcons].d->vc_s_reverse)
#define	ulcolor		(vc_cons[currcons].d->vc_ulcolor)
#define	halfcolor	(vc_cons[currcons].d->vc_halfcolor)
#ifdef CONFIG_GDC_CONSOLE
# define def_attr	(vc_cons[currcons].d->vc_def_attr)
# define ul_attr	(vc_cons[currcons].d->vc_ul_attr)
# define half_attr	(vc_cons[currcons].d->vc_half_attr)
# define bold_attr	(vc_cons[currcons].d->vc_bold_attr)
#endif
#define tab_stop	(vc_cons[currcons].d->vc_tab_stop)
#define palette		(vc_cons[currcons].d->vc_palette)
#define bell_pitch	(vc_cons[currcons].d->vc_bell_pitch)
#define bell_duration	(vc_cons[currcons].d->vc_bell_duration)
#define cursor_type	(vc_cons[currcons].d->vc_cursor_type)
#define display_fg	(vc_cons[currcons].d->vc_display_fg)
#define complement_mask (vc_cons[currcons].d->vc_complement_mask)
#define s_complement_mask (vc_cons[currcons].d->vc_s_complement_mask)
#define hi_font_mask	(vc_cons[currcons].d->vc_hi_font_mask)
#ifdef CONFIG_PC9800
#define kanji_mode     (vc_cons[currcons].d->vc_kanji_mode)
#define s_kanji_mode   (vc_cons[currcons].d->vc_s_kanji_mode)
#define kanji_char1    (vc_cons[currcons].d->vc_kanji_char1)
#define translate_ex   (vc_cons[currcons].d->vc_translate_ex)
#define G0_charset_ex  (vc_cons[currcons].d->vc_G0_charset_ex)
#define G1_charset_ex  (vc_cons[currcons].d->vc_G1_charset_ex)
#define saved_G0_ex    (vc_cons[currcons].d->vc_saved_G0_ex)
#define saved_G1_ex    (vc_cons[currcons].d->vc_saved_G1_ex)
#define kanji_jis_mode (vc_cons[currcons].d->vc_kanji_jis_mode)
#define s_kanji_jis_mode (vc_cons[currcons].d->vc_s_kanji_jis_mode)
#define pc98_addbuf	(vc_cons[currcons].d->vc_pc98_addbuf)
#endif

#define vcmode		(vt_cons[currcons]->vc_mode)

#define structsize	(sizeof(struct vc_data) + sizeof(struct vt_struct))
